#define LEVEL_WIDTH 1360
#define LEVEL_HEIGHT 960
#define SCREEN_WIDTH 680
#define SCREEN_HEIGHT 480
#define DEADZONE_LEFT_RIGHT WINDOW_WIDTH/2
#define DEADZONE_TOP_BOTTOM WINDOW_HEIGHT/2

#define WINDOW_WIDTH 680
#define WINDOW_HEIGHT 480